version: '3.4'

services:
  fakeinstagram:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
#      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8080:80"
#      - "44325:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/